apiVersion: v1
kind: Service
metadata:
  name: kafkaui
  namespace: default
spec:
  type: NodePort
  selector:
    app: kafkaui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaui
  template:
    metadata:
      labels:
        app: kafkaui
    spec:
      containers:
        - name: kafkaui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 750m
              memory: 768Mi
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: managed-a
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-0.managed-a.svc.cluster.local:9092
            - name: KAFKA_CLUSTERS_1_NAME
              value: managed-b
            - name: KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS
              value: kafka-0.managed-b.svc.cluster.local:9092
