apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: managed-a
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9092
    - name: controller
      port: 9093
    - name: external
      port: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0
  namespace: managed-a
spec:
  selector:
    app: kafka
    apps.kubernetes.io/pod-index: "0"
  ports:
    - name: plaintext
      port: 9092
    - name: controller
      port: 9093
    - name: external
      port: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  namespace: managed-a
spec:
  selector:
    app: kafka
    apps.kubernetes.io/pod-index: "1"
  ports:
    - name: plaintext
      port: 9092
    - name: controller
      port: 9093
    - name: external
      port: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  namespace: managed-a
spec:
  selector:
    app: kafka
    apps.kubernetes.io/pod-index: "2"
  ports:
    - name: plaintext
      port: 9092
    - name: controller
      port: 9093
    - name: external
      port: 9094
