apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
  namespace: default
  labels:
    app: writer
spec:
  selector:
    matchLabels:
      app: writer
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: writer
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: writer
          image: localhost:32000/chat-writer:latest
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 300Mi
          envFrom:
            - configMapRef:
                name: db-connection
            - configMapRef:
                name: kafka-a-connection
            - configMapRef:
                name: redis-connection
          env:
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_GROUP_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: KAFKA_CHATS_GROUP_ID
              value: chats-$(KAFKA_GROUP_ID)
      restartPolicy: Always
