apiVersion: v1
kind: Service
metadata:
  name: writer-headless
  namespace: default
spec:
  selector:
    app: writer
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: writer
  namespace: default
spec:
  selector:
    matchLabels:
      app: writer
  serviceName: writer-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: writer
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: writer
          image: localhost:32000/chat-writer:latest
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 300Mi
          envFrom:
            - configMapRef:
                name: db-connection
            - configMapRef:
                name: kafka-a-connection
            - configMapRef:
                name: redis-connection
          env:
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_GROUP_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: KAFKA_CHATS_GROUP_ID
              value: chats-$(KAFKA_GROUP_ID)
      restartPolicy: Always
